version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ecommerce-db2
    environment:
      POSTGRES_DB: shop-app-2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dawid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: